# Generated by Django 5.0.6 on 2024-05-17 23:14

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_ativo_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ativo',
            name='usuario',
            field=models.ForeignKey(default=core.models.Ativo.get_default_user_id, on_delete=django.db.models.deletion.CASCADE, related_name='ativos', to=settings.AUTH_USER_MODEL),
        ),
    ]
