# Generated by Django 5.0.6 on 2024-05-18 17:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_ativo_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='ativo',
            name='cotacao',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='ativo',
            name='dividend_yield',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='ativo',
            name='liquidez_diaria',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='ativo',
            name='p_vp',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='ativo',
            name='variacao_12m',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='ativo',
            name='price',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='ativo',
            name='quant',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
