# Generated by Django 5.0.6 on 2024-05-18 17:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_ativo_cotacao_ativo_dividend_yield_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ativo',
            name='quant',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
