# Generated by Django 5.0.6 on 2024-05-18 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_ativo_quant'),
    ]

    operations = [
        migrations.AddField(
            model_name='ativo',
            name='p_l',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='ativo',
            name='tipo',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='ativo',
            name='variacao_24m',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='ativo',
            name='variacao_60m',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='ativo',
            name='cotacao',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='ativo',
            name='dividend_yield',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='ativo',
            name='p_vp',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='ativo',
            name='variacao_12m',
            field=models.CharField(default='', max_length=25),
        ),
    ]
