# Generated by Django 5.0.6 on 2024-05-20 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_ativo_quant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ativo',
            name='capitalizacao',
        ),
        migrations.RemoveField(
            model_name='ativo',
            name='reais',
        ),
    ]
