# Generated by Django 5.0.6 on 2024-05-20 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_ativo_quant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ativo',
            name='quant',
            field=models.FloatField(default=0),
        ),
    ]
