# Generated by Django 5.0.6 on 2024-05-22 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_ativo_quant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ativo',
            name='codigo',
            field=models.CharField(max_length=10),
        ),
    ]
