# Generated by Django 5.0.6 on 2024-05-22 20:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_userprofile_last_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_active',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
